spring.application.name=gestor-finanzas

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_finanzas?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Mastantuono30
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Serve static files from /static
spring.web.resources.static-locations=classpath:/static/

server.port=8080
